export const orderList = [
  {
    orderId: "ID12735",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "delivered",
    location: "San Diego",
    deliveryDate: "10/12/2023",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
    products: [
      {
        name: "Salsa African Attire",
        price: 129,
        description:
          "The Salsa African Attire is a beautiful and vibrant dress that blends traditional African fashion with a modern twist. This dress is made from Show more...",
        size: "medium",
        quantity: 2,
        material: "Real English Wax",
        note: "Lorem ipsum dolor sit amet consectetur. Aliquam arcu ac fringilla fermentum pharetra amet. Praesent ullamcorper non vel sapien varius lacus adipiscing.",
        measurement: {
          waist: 30,
          height: 89,
          hip: 50,
          bust: 34,
        },
      },
      {
        name: "Salsa African Attire",
        price: 129,
        description:
          "The Salsa African Attire is a beautiful and vibrant dress that blends traditional African fashion with a modern twist. This dress is made from Show more...",
        size: "medium",
        quantity: 2,
        material: "Real English Wax",
        note: "Lorem ipsum dolor sit amet consectetur. Aliquam arcu ac fringilla fermentum pharetra amet. Praesent ullamcorper non vel sapien varius lacus adipiscing.",
        measurement: {
          waist: 30,
          height: 89,
          hip: 50,
          bust: 34,
        },
      },
    ],
  },
  {
    orderId: "ID12736",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "processing",
    deliveryDate: "10/12/2023",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
    products: [
      {
        name: "Salsa African Attire",
        price: 129,
        description:
          "The Salsa African Attire is a beautiful and vibrant dress that blends traditional African fashion with a modern twist. This dress is made from Show more...",
        size: "medium",
        quantity: 2,
        material: "Real English Wax",
        note: "Lorem ipsum dolor sit amet consectetur. Aliquam arcu ac fringilla fermentum pharetra amet. Praesent ullamcorper non vel sapien varius lacus adipiscing.",
        measurement: {
          waist: 30,
          height: 89,
          hip: 50,
          bust: 34,
        },
      },
    ],
  },
  {
    orderId: "ID12737",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "cancelled",
    deliveryDate: "10/12/2023",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
    products: [
      {
        name: "Salsa African Attire",
        price: 129,
        description:
          "The Salsa African Attire is a beautiful and vibrant dress that blends traditional African fashion with a modern twist. This dress is made from Show more...",
        size: "medium",
        quantity: 2,
        material: "Real English Wax",
        note: "Lorem ipsum dolor sit amet consectetur. Aliquam arcu ac fringilla fermentum pharetra amet. Praesent ullamcorper non vel sapien varius lacus adipiscing.",
        measurement: {
          waist: 30,
          height: 89,
          hip: 50,
          bust: 34,
        },
      },
    ],
  },
  {
    orderId: "ID12738",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "processing",
    deliveryDate: "10/12/2023",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
  },
  {
    orderId: "ID12739",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "delivered",
    location: "London, Uk",
    deliveryDate: "10/12/2023",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
  },
  {
    orderId: "ID12740",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "cancelled",
    deliveryDate: "10/12/2023",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
  },
  {
    orderId: "ID12741",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "delivered",
    deliveryDate: "10/12/2023",
    location: "San Francisco",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
  },
  {
    orderId: "ID12742",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "delivered",
    location: "Los Angeles",
    deliveryDate: "10/12/2023",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
  },
  {
    orderId: "ID12743",
    customerName: "Raji Adeoye",
    customerEmail: "myemail@gmail.com",
    price: 129,
    status: "delivered",
    location: "Miamia",
    deliveryDate: "10/12/2023",
    shippingAddress: "123, Jeweess Bridge Apt. 174 London, UK.",
    phoneNumber: "+1(474) 746-3918",
  },
];
